version: '3'

services:
  mysql:
    image: mysql:8.0.30-debian
    container_name: db_wallet
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wallet
    ports:
      - 3306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql